<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Player</title>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->HeadLink()->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.css')?>

        <?php
        echo $this->headScript()                
                ->prependFile($this->basePath() . '/js/player.js')                
                ->prependFile('https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.custom.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>
        
        <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
        
    </head>
    <body>      
        <div class="main">
            <div class="top">
                <h1>Player</h1>
            </div>
            <div class="content">
                <?php echo $this->content; ?>    
            </div>
            <div class="footer">
                
            </div>
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
